### ISSUE TITLE
Incorrect description in "Connect" section of the about page

### ISSUE THREAD

**Issue by wyuting0** [TimWitzdam/astro-minimal-portfolio-template#6]
In the About page template, the "Connect" section displays the same description as the "Work" section. This is due to using `aboutPageContent.work.description` for both sections instead of using` aboutPageContent.connect.description` for the "Connect" section.

This issue is in the `src/pages/about.astro file` section. To fix, change the reference for the description in the "Connect" section to use `aboutPageContent.connect.description` instead of `aboutPageContent.work.description`.

![Screenshot 2024-12-23 203120](https://github.com/user-attachments/assets/d1ae0f19-a3c0-46c5-8587-790185cc36e9)
<img width="695" alt="Screenshot 2024-12-23 202735" src="https://github.com/user-attachments/assets/06fff482-51c4-45f9-9271-0e0c7865c91a" />

**Comment by TimWitzdam** [comment]
Hey, thanks for opening this issue and letting me know!
Somehow I missed the mail from GitHub, that's why I'm just replying so late.

This issue has been fixed with 45f722f and is already present in the newest [v1.0.5](https://github.com/TimWitzdam/astro-minimal-portfolio-template/releases/tag/v1.0.5) release.
